language: generic

sudo: false

matrix:
  include:
    - { os: linux, env: PYTHON_VERSION=2.7 }
    - { os: linux, env: PYTHON_VERSION=3.5 }
    - { os: linux, env: PYTHON_VERSION=3.6 }
    - { os: osx, env: PYTHON_VERSION=2.7 }
    - { os: osx, env: PYTHON_VERSION=3.5 }

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum; fi
  - source devtools/travis-ci/install.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda env create -n test-environment python=$PYTHON_VERSION -f environment.yml
  - source activate test-environment
  - pip install -e .

script:
  - pytest -v --cov=msibi  --cov-report= --pyargs msibi

after_success:
  - coveralls
