name: msibi-docs
channels:
  - conda-forge
dependencies:
  - sphinx==7.2.4
  - sphinx_rtd_theme==1.3.0
  - freud >= 3.0
  - gsd >= 3.0
  - hoomd >= 4.0
  - python >= 3.10
  - pandas
  - numpy <= 2.0
  - cmeutils >= 1.3
  - more-itertools
